### ISSUE TITLE
Duplicate crudini install

### ISSUE THREAD

**Issue by hieulq** [vietstacker/OpenStack-Mitaka-Scripts#2]
com1-ceilometer và com1-prepare.sh đều thấy có pip install crudini, có cần thiết phải install 2 lần như vậy không ?

**Comment by congto** [comment]
@hieulq bỏ trên com1-ceilomter đi được nhé.
@diendt: Anh bỏ dòng trên Hiếu comment rồi commit một thể nhé, có trong file com1-prepare.sh rồi anh ạ

**Comment by hieulq** [comment]
Done !
