### ISSUE TITLE
Fix option [lvm]  of ctl-7-cinder.sh

### ISSUE THREAD

**Issue by congto** [vietstacker/OpenStack-Mitaka-Scripts#5]
Tham số volume_driver trong  [lvm] section bi sai @hieulq @diendt . Em fix lại rồi mn nhé.

**Comment by hieulq** [comment]
:+1: 
Nhưng mà commit rồi lại còn mở issue để khoe nữa, yêu cầu sau không được làm màu thế này nhé, già rồi mà lắm trò quá :))
