### ISSUE TITLE
Uncomment 127.0.1.1 in /etc/hosts

### ISSUE THREAD

**Issue by jomeier** [vietstacker/OpenStack-Mitaka-Scripts#7]
Hi,

the title says everything. If you don't uncomment this line, there will be connection problems (in my case I couldn't connect to the mysql database).

Best regards,

Josef

**Comment by congto** [comment]
Thank @jomeier !
I fixed your issue. Plz, check 
https://github.com/vietstacker/OpenStack-Mitaka-Scripts/commit/8d8d3086ba6f1041e9627ffa6ecfbfdb92ace5b2

**Comment by jomeier** [comment]
It's working.
